[package]
name = "cq"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.5.0"
ark-poly = "0.5.0"
ark-ff = "0.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
rand = "0.8.5"
ark-bls12-381 = "0.5.0"
sha2 = "0.9.1"
thiserror = "2.0.5"